#!/bin/sh
setup_ssid()
{
    local r="radio$1"
    
    if ! uci show wireless.${r} >/dev/null 2>&1; then
        return
    fi
    local s="wlan$1"
    logger "default-wifi: setup $1's ssid"
    local mac=`ifconfig ${s} | grep "HWaddr" | awk '{print $5}'`
    local wifimac=`echo ${mac}|awk -F ":" '{print $4""$5""$6 }'|tr A-Z a-z|cut -c4-`
    # uci set wireless.${r}.disabled=0
    uci set wireless.${r}.country=CN
    # uci set wireless.${r}.channel=149
    if [ `uci get wireless.${r}.channel` -lt 14 ]; then
        uci set wireless.${r}.channel=11
        uci set wireless.default_${r}.ssid=EZ-2.4G
    else
        uci set wireless.${r}.channel=149
        uci set wireless.default_${r}.ssid=EZ-5G
    fi
    uci set wireless.default_${r}.encryption='psk2'
    uci set wireless.default_${r}.key='12345678'
    uci commit
}
WIFI_NUM=`find /sys/class/net/ -name wlan* | wc -l`
if [ ${WIFI_NUM} -gt 0 ]; then
    # update /etc/config/wireless
    for i in `seq 0 ${WIFI_NUM}`; do
        setup_ssid ${i}
    done
fi

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q set system.@imm_init[0].lang="1"
fi
if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
	uci -q set fstab.@global[0].anon_mount="1"
	uci -q commit fstab
	uci -q set system.@imm_init[0].anon_mount="1"
fi
uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	delete system.ntp.server
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'
EOF
uci commit system
uci set luci.main.mediaurlbase='/luci-static/kucat'
uci commit luci
sed -i 's,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf
# opkg mirror
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

# upnp
uci set upnpd.config.enabled='1'
uci commit upnpd
/etc/init.d/miniupnpd restart
# /etc/init.d/dockerd stop
# firewall
uci set firewall.@defaults[0].fullcone='1'
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall

ln -sf "/sbin/ip" "/usr/bin/ip"

[ ! -e "/bin/bash" ] || sed -i "s|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g" "/etc/passwd"
sed -i '/lcp-echo/d' /etc/ppp/options
echo "lcp-echo-failure 10" >>  /etc/ppp/options 
echo "lcp-echo-interval 200" >>  /etc/ppp/options
sed -i 's/immortalwrt/openwrt/g' /etc/config/luci
sed -i 's/immortalwrt/openwrt/g' /etc/opkg/distfeeds.conf

sed -i '/coremark/d' /etc/crontabs/root
crontab /etc/crontabs/root
[ -f /etc/ezopenwrt_version ]  && { 
    sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
    new_DISTRIB_REVISION=`cat  /etc/ezopenwrt_version`
    echo "DISTRIB_DESCRIPTION='EzOpWrt "${new_DISTRIB_REVISION}"'" >> /etc/openwrt_release
}
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
uci set wireless.radio0.disabled=0
uci set wireless.radio1.disabled=0
uci commit wireless
wifi up

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
